services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - 8080:80
    volumes:
      - "/home/vagrant/dev_ops_test_app:/var/www/html"
    networks:
      - app-network

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: Password1

networks:
  app-network:
