services:
  web:
    image: copy123aweq/bgapp-web
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - 8080:80
    volumes:
      - "/home/vagrant/dev_ops_test_app/web:/var/www/html"
    networks:
      - app-network

  db:
    image: copy123aweq/bgapp-db
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: Password1

networks:
  app-network:
